### ISSUE TITLE
Feature: Using proper http graceful shutdown.

### ISSUE THREAD

**Issue by KevinJCross** [tedsuo/ifrit#37]
Its been a while since there was any activity on this project but us in the cf autoscaler project are looking to either move away from ifrit or enhance this because we are seeing some stalls in our shutdowns (and this is quite old). I was looking at the shutdown code for the http server and its got some  complexity, which was needed to be back in the day. 
We now have the `server.shutdown()` (2017)  function which does a proper gracefull shutdown. I would suggest we use this and a context timeout with a forced .close() if it times out, which would simplify it considerably (no need to keep track of connections).

Thoughts ?
Plus its time to have a mod file and a release versioning to keep up with the go environment. 
Oh BTW the tests didnt pass last time I tried running them :/.

**Comment by tedsuo** [comment]
Hi Kevin. Since CF is the primary end user of ifrit, I suggest forking or taking over maintenance of this project. I am happy to review and accept pull requests – which I do quickly – but I am no longer developing ifrit at this time.

**Comment by evanchaoli** [comment]
I have noticed this issue with concourse/concourse as well. Let me try to create a fix.

**Comment by tedsuo** [comment]
Merged.

FYI @KevinJCross, years ago I proposed improving ifrit to be streamlined and require less boilerplate. But, from the cloud foundry side, there was zero interest. https://github.com/tedsuo/ifrit/issues/30

I avoid making changes, including adding a mod file, because I do not want to accidentally trigger an issue within cloud foundry, especially one which may require touching all of the various services which use ifrit.

If there is interest in modernizing ifrit, I am happy to help with that. But I would need clarity on whether the cloud foundry crew is aware of the changes, and on board with making a v2.
